In [54]:
import openpyxl
import numpy as np
from numpy.random import randn

In [3]:
wb = openpyxl.load_workbook('FTSE_1984_2012.xlsx')
sheetNames = wb.sheetnames
# Assumes 1 sheet name
sheet = wb[sheetNames[0]]
rows = sheet.rows
# rows is a generator, so it is directly iterable
open_price = [row[1].value for row in rows]

In [5]:
open_price[:10]

['Open',
 5899.9,
 5905.7,
 5852.4,
 5895.5,
 5875.9,
 5890.3,
 5892.2,
 5901.1,
 5796.1]

In [9]:
wb = openpyxl.load_workbook('FTSE_1984_2012.xlsx')
sheetNames = wb.sheetnames
# Assumes 1 sheet name
sheet = wb[sheetNames[0]]
# Use list to store data
open_price = []
# Changes since access is via memory efficient iterator
# Note () on iter_rows
for row in sheet.iter_rows():
    # Must use internal_value
    open_price.append(row[1].internal_value)
# Burn first row and convert to array
open_price = np.array(open_price[1:])

In [10]:
open_price[:10]

array([5899.9, 5905.7, 5852.4, 5895.5, 5875.9, 5890.3, 5892.2, 5901.1,
       5796.1, 5790.7])

In [12]:
from numpy import array
f = open('IBM_TAQ.txt', 'r')
line = f.readline()
# Burn the first list as a header
line = f.readline()
date = []
time = []
price = []
volume = []
while line:
    data = line.split(',')
    date.append(int(data[1]))
    price.append(float(data[3]))
    volume.append(int(data[4]))
    t = data[2]
    time.append(int(t.replace(':','')))
    line = f.readline()
# Convert to arrays, which are more useful than lists
# for numeric data
date = array(date)
price = array(price)
volume = array(volume)
time = array(time)
allData = array([date,price,volume,time])
f.close()

In [13]:
allData

array([[2.0070103e+07, 2.0070103e+07, 2.0070103e+07, ..., 2.0070131e+07,
        2.0070131e+07, 2.0070131e+07],
       [9.7180000e+01, 9.6600000e+01, 9.7170000e+01, ..., 9.9130000e+01,
        9.9130000e+01, 9.9130000e+01],
       [1.0000000e+02, 3.7320000e+05, 1.0000000e+03, ..., 5.0000000e+02,
        1.7000000e+03, 7.0000000e+02],
       [9.3003000e+04, 9.3008000e+04, 9.3008000e+04, ..., 1.5595900e+05,
        1.6000000e+05, 1.6000000e+05]])

In [15]:
# Chpter 8 exercises

In [16]:
import numpy as np

In [22]:
x=np.arange(12.0)

In [23]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
x_copy=np.copy(x)
x_copy.shape=1,12

In [25]:
x_copy

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])

In [27]:
x_copy=np.copy(x)
x_copy.reshape((1,12))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])

In [28]:
x_copy=np.copy(x)
x_copy.shape=2,6

In [29]:
x_copy

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [30]:
x_copy=np.copy(x)
x_copy.reshape((2,6))

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [31]:
x_copy=np.copy(x)
x_copy.shape=3,4

In [32]:
x_copy

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
x_copy=np.copy(x)
x_copy.reshape((3,4))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [34]:
x_copy=np.copy(x)
x_copy.shape=4,3
print(x_copy)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [35]:
x_copy=np.copy(x)
x_copy.reshape((4,3))

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [36]:
x_copy=np.copy(x)
x_copy.shape=6,2
print(x_copy)

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


In [37]:
x_copy=np.copy(x)
x_copy.reshape((6,2))

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]])

In [38]:
x_copy=np.copy(x)
x_copy.shape=2,2,3
print(x_copy)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [39]:
x_copy=np.copy(x)
x_copy.reshape((2,2,3))

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [40]:
x_original=x_copy.ravel()

In [41]:
x_original

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [44]:
x=np.reshape(np.arange(12.0),(4,3))

In [45]:
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [51]:
temp_arr=x.ravel()
print(temp_arr[1],temp_arr[3],temp_arr[5],temp_arr[7],temp_arr[9],temp_arr[11])

1.0 3.0 5.0 7.0 9.0 11.0


In [52]:
temp_arr=x.flatten()
print(temp_arr[1],temp_arr[3],temp_arr[5],temp_arr[7],temp_arr[9],temp_arr[11])

1.0 3.0 5.0 7.0 9.0 11.0


In [53]:
print(x.flat[1],x.flat[3],x.flat[5],x.flat[7],x.flat[9],x.flat[11])

1.0 3.0 5.0 7.0 9.0 11.0


In [55]:
from numpy.random import randn
x = np.array([[1,2,3,4]])
y = np.reshape(x,(4,1))
b = np.broadcast_arrays(x,y)

print(b[0],b[1])

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [56]:
x = randn(2,2)
y = randn(1,1)
z = randn(3,2)
print(x)
print(y)
print(z)

q = np.hstack((y,y,y))
s = np.vstack((q,q))
e = np.hstack((x,s))

c = z.T
r = np.vstack((c,q))
t = np.hstack((z,r))

w = np.vstack((e,t))
print(w)

[[ 0.54067336 -0.06675523]
 [-2.19305737  0.11759694]]
[[-0.84123836]]
[[-0.17308159 -0.33439699]
 [ 0.89999265 -1.01196602]
 [ 0.26515842  1.78365348]]
[[ 0.54067336 -0.06675523 -0.84123836 -0.84123836 -0.84123836]
 [-2.19305737  0.11759694 -0.84123836 -0.84123836 -0.84123836]
 [-0.17308159 -0.33439699 -0.17308159  0.89999265  0.26515842]
 [ 0.89999265 -1.01196602 -0.33439699 -1.01196602  1.78365348]
 [ 0.26515842  1.78365348 -0.84123836 -0.84123836 -0.84123836]]


In [60]:
x = np.reshape(np.arange(12.0),(2,2,3))
print(x)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [61]:
x.squeeze()

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [63]:
eps=np.finfo(float).eps

In [64]:
eps2=np.log(np.exp(1000))

<ipython-input-64-9c78288c61d4>:1: RuntimeWarning: overflow encountered in exp
  eps2=np.log(np.exp(1000))


In [65]:
eps

2.220446049250313e-16

In [66]:
eps2

inf

In [69]:
eps/10 == 0

False

In [70]:
eps/10

2.2204460492503132e-17

In [71]:
x=1+eps/10 -1

In [72]:
x==0

True

In [73]:
1-eps/10 -1 == 0

True

In [74]:
1-1-eps/10 == 0

False