In [1]:
import pandas as pd
import numpy as np

In [2]:
dataframe=pd.read_excel('exercise3.xls')

In [3]:
dataframe

Date       XOM     SP500
0    1991-01-03  0.005806 -0.014005
1    1991-01-04  0.010079 -0.002831
2    1991-01-07 -0.012978 -0.017473
3    1991-01-08 -0.002907 -0.001713
4    1991-01-09 -0.016141 -0.010888
...         ...       ...       ...
5036 2010-12-27 -0.002675  0.000612
5037 2010-12-28  0.005624  0.000771
5038 2010-12-29 -0.000701  0.001009
5039 2010-12-30 -0.000140 -0.001509
5040 2010-12-31 -0.003232 -0.000191

[5041 rows x 3 columns]

In [6]:
(dataframe.XOM<0).sum()

2346

In [7]:
(dataframe.SP500<0).sum()

2360

In [16]:
dataframe['both_neg']=(dataframe.XOM<0) & (dataframe.SP500<0)

In [21]:
dataframe.both_neg=dataframe.both_neg.astype(int)

In [22]:
dataframe

Date       XOM     SP500  both_neg
0    1991-01-03  0.005806 -0.014005         0
1    1991-01-04  0.010079 -0.002831         0
2    1991-01-07 -0.012978 -0.017473         1
3    1991-01-08 -0.002907 -0.001713         1
4    1991-01-09 -0.016141 -0.010888         1
...         ...       ...       ...       ...
5036 2010-12-27 -0.002675  0.000612         0
5037 2010-12-28  0.005624  0.000771         0
5038 2010-12-29 -0.000701  0.001009         0
5039 2010-12-30 -0.000140 -0.001509         1
5040 2010-12-31 -0.003232 -0.000191         1

[5041 rows x 4 columns]

In [23]:
dataframe.corr()

XOM     SP500  both_neg
XOM       1.000000  0.592257 -0.569279
SP500     0.592257  1.000000 -0.565404
both_neg -0.569279 -0.565404  1.000000

In [24]:
dataframe[dataframe.both_neg>0].corr()

XOM     SP500  both_neg
XOM       1.000000  0.619798       NaN
SP500     0.619798  1.000000       NaN
both_neg       NaN       NaN       NaN

In [29]:
dataframe[(dataframe.XOM<0) | (dataframe.SP500<0)].corr()

XOM     SP500  both_neg
XOM       1.000000  0.320166 -0.462756
SP500     0.320166  1.000000 -0.472787
both_neg -0.462756 -0.472787  1.000000

In [30]:
def myall(y):
    for element in y:
        if not element:
            return False
    return True

In [31]:
def myany(x):
    for element in x:
        if element:
            return True
    return False

In [32]:
x=np.arange(10.0)
y=np.reshape(np.arange(25.0),(5,5))
z=np.reshape(np.arange(64.0),(4,4,4))

In [36]:
x[4]

4.0

In [41]:
x[np.argwhere(x==4.0)[0][0]]

4.0

In [44]:
np.extract(x==4.0,x)[0]

4.0

In [47]:
x[x==4.0][0]

4.0

In [48]:
x[1]

1.0

In [52]:
x[:5]

array([0., 1., 2., 3., 4.])

In [51]:
x[0:5]

array([0., 1., 2., 3., 4.])

In [53]:
x[5:]

array([5., 6., 7., 8., 9.])

In [54]:
x[-5:]

array([5., 6., 7., 8., 9.])

In [56]:
y[[2,4],:]

array([[10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.]])

In [61]:
np.concatenate([[y[2]],[y[4]]])

array([[10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.]])

In [64]:
y[2::2]

array([[10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.]])

In [65]:
y_5remainder=y%5

In [66]:
y_5remainder

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [79]:
y_7remainder=y%7

In [80]:
y_7remainder

array([[0., 1., 2., 3., 4.],
       [5., 6., 0., 1., 2.],
       [3., 4., 5., 6., 0.],
       [1., 2., 3., 4., 5.],
       [6., 0., 1., 2., 3.]])

In [81]:
y5_row=[i for i,elem in enumerate(y_5remainder) if 0 in elem]

In [82]:
y5_row

[0, 1, 2, 3, 4]

In [83]:
y7_row=[i for i,elem in enumerate(y_7remainder) if 0 in elem]

In [84]:
y7_row

[0, 1, 2, 4]

In [85]:
result=list(set(y5_row)&set(y7_row))

In [86]:
result

[0, 1, 2, 4]

In [87]:
y[result]

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [20., 21., 22., 23., 24.]])

In [91]:
z[:,[2,3],:]

array([[[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[24., 25., 26., 27.],
        [28., 29., 30., 31.]],

       [[40., 41., 42., 43.],
        [44., 45., 46., 47.]],

       [[56., 57., 58., 59.],
        [60., 61., 62., 63.]]])