In [2]:
import numpy as np
import scipy

In [3]:
u=np.array([1,1,2,3,5,8])
v=np.array([[1],[1],[2],[3],[5],[8]])
x=np.array([[1,0],[0,1]])
y=np.array([[1,2],[3,4]])
z=np.array([[1,2,1,2],[3,4,3,4],[1,2,1,2]])
w=np.array([[x,x],[y,y]])

In [4]:
w

array([[[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]],


       [[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]]])

In [7]:
w[0,0]

array([[1, 0],
       [0, 1]])

In [8]:
w[0,1]

array([[1, 0],
       [0, 1]])

In [9]:
w[:,0]

array([[[1, 0],
        [0, 1]],

       [[1, 2],
        [3, 4]]])

In [10]:
w[:,1]

array([[[1, 0],
        [0, 1]],

       [[1, 2],
        [3, 4]]])

In [12]:
z[:2,:2]

array([[1, 2],
       [3, 4]])

In [13]:
z[:2,2:]

array([[1, 2],
       [3, 4]])

In [14]:
u+v.T

array([[ 2,  2,  4,  6, 10, 16]])

In [21]:
(u+v.T).T

array([[ 2],
       [ 2],
       [ 4],
       [ 6],
       [10],
       [16]])

In [22]:
v*u

array([[ 1,  1,  2,  3,  5,  8],
       [ 1,  1,  2,  3,  5,  8],
       [ 2,  2,  4,  6, 10, 16],
       [ 3,  3,  6,  9, 15, 24],
       [ 5,  5, 10, 15, 25, 40],
       [ 8,  8, 16, 24, 40, 64]])

In [23]:
u*v

array([[ 1,  1,  2,  3,  5,  8],
       [ 1,  1,  2,  3,  5,  8],
       [ 2,  2,  4,  6, 10, 16],
       [ 3,  3,  6,  9, 15, 24],
       [ 5,  5, 10, 15, 25, 40],
       [ 8,  8, 16, 24, 40, 64]])

In [25]:
np.matmul(x,y)

array([[1, 2],
       [3, 4]])

In [26]:
a=[3,2]
b=[[3],[2]]
c=[3,2,1,0]
d=[[3],[2],[1],[0]]

In [28]:
a+v

array([[ 4,  3],
       [ 4,  3],
       [ 5,  4],
       [ 6,  5],
       [ 8,  7],
       [11, 10]])

In [29]:
a+x

array([[4, 2],
       [3, 3]])

In [30]:
a+y

array([[4, 4],
       [6, 6]])

In [31]:
a+w

array([[[[4, 2],
         [3, 3]],

        [[4, 2],
         [3, 3]]],


       [[[4, 4],
         [6, 6]],

        [[4, 4],
         [6, 6]]]])

In [32]:
b+u

array([[ 4,  4,  5,  6,  8, 11],
       [ 3,  3,  4,  5,  7, 10]])

In [34]:
b+x

array([[4, 3],
       [2, 3]])

In [35]:
b+y

array([[4, 5],
       [5, 6]])

In [36]:
b+w

array([[[[4, 3],
         [2, 3]],

        [[4, 3],
         [2, 3]]],


       [[[4, 5],
         [5, 6]],

        [[4, 5],
         [5, 6]]]])

In [38]:
c+v

array([[ 4,  3,  2,  1],
       [ 4,  3,  2,  1],
       [ 5,  4,  3,  2],
       [ 6,  5,  4,  3],
       [ 8,  7,  6,  5],
       [11, 10,  9,  8]])

In [41]:
c+z

array([[4, 4, 2, 2],
       [6, 6, 4, 4],
       [4, 4, 2, 2]])

In [42]:
d+u

array([[ 4,  4,  5,  6,  8, 11],
       [ 3,  3,  4,  5,  7, 10],
       [ 2,  2,  3,  4,  6,  9],
       [ 1,  1,  2,  3,  5,  8]])

In [49]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.r_[0:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.linspace(4,13,10)

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])

In [56]:
np.arange(4,14,1)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [58]:
np.r_[4:14]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [60]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [66]:
np.arange(0,1.1,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [65]:
np.r_[0:1.1:0.25]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [67]:
np.linspace(0,-5,6)

array([ 0., -1., -2., -3., -4., -5.])

In [70]:
np.arange(0,-6,-1)

array([ 0, -1, -2, -3, -4, -5])

In [72]:
np.r_[0:-6:-1]

array([ 0, -1, -2, -3, -4, -5])

In [73]:
y=[0, 0.5, 1.5, 2.5, 1.0,1.0001,-0.5,-1,-1.5,-2.5]

In [74]:
np.round(y)

array([ 0.,  0.,  2.,  2.,  1.,  1., -0., -1., -2., -2.])

In [75]:
np.ceil(y)

array([ 0.,  1.,  2.,  3.,  1.,  2., -0., -1., -1., -2.])

In [76]:
np.floor(y)

array([ 0.,  0.,  1.,  2.,  1.,  1., -1., -1., -2., -3.])

In [77]:
x=np.random.randn(20)

In [78]:
x

array([-1.20407173,  0.84718048,  0.60563953, -0.96116219,  1.90976722,
        0.52094825,  0.41868517, -0.57696411, -1.09667326,  1.4804518 ,
        0.45319046,  0.23082427, -0.92045221, -1.80679797,  0.53557678,
       -0.87830747, -1.01963175,  0.08656671, -0.15473362, -1.60952648])

In [79]:
np.cumsum(x)

array([-1.20407173, -0.35689125,  0.24874828, -0.7124139 ,  1.19735332,
        1.71830157,  2.13698674,  1.56002263,  0.46334937,  1.94380117,
        2.39699163,  2.6278159 ,  1.70736369, -0.09943428,  0.43614251,
       -0.44216496, -1.46179672, -1.37523001, -1.52996363, -3.13949011])

In [80]:
np.diff(np.cumsum(x))

array([ 0.84718048,  0.60563953, -0.96116219,  1.90976722,  0.52094825,
        0.41868517, -0.57696411, -1.09667326,  1.4804518 ,  0.45319046,
        0.23082427, -0.92045221, -1.80679797,  0.53557678, -0.87830747,
       -1.01963175,  0.08656671, -0.15473362, -1.60952648])

In [85]:
np.concatenate([np.cumsum(x)[:1],np.diff(np.cumsum(x))])

array([-1.20407173,  0.84718048,  0.60563953, -0.96116219,  1.90976722,
        0.52094825,  0.41868517, -0.57696411, -1.09667326,  1.4804518 ,
        0.45319046,  0.23082427, -0.92045221, -1.80679797,  0.53557678,
       -0.87830747, -1.01963175,  0.08656671, -0.15473362, -1.60952648])

In [86]:
np.absolute([0.0,-3.14,3+4j])

array([0.  , 3.14, 5.  ])

In [95]:
x=np.array([-4,2,-9,-8,10])

In [96]:
np.sort(x)

array([-9, -8, -4,  2, 10])

In [97]:
x.sort()

In [98]:
x

array([-9, -8, -4,  2, 10])

In [99]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
np.exp(np.identity(5))

array([[2.71828183, 1.        , 1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 2.71828183]])